name: JobMasterApi
on:
 push: 
   branches: ["main"]

jobs:
  Build:
    runs-on: ubintu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@4
    - name: Setup .NET
      uses: actions/setup-dotnet@4
      with: 
        dotnet-version: 8.0.x
      
 
